cc_test(
    name = "test_greeting",
    size = "small",
    srcs = ["test_greeting.cc"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "//lib:greeting"
    ],
)
