# Make this package visible to other packages in this repository.
package(default_visibility = [
    "//app:__pkg__",
    "//test:__pkg__",
    ])

cc_library(
    name = "greeting",
    srcs = ["greeting.cc"],
    hdrs = ["greeting.h"],
)
